import { useEffect, useState } from "react";
import { CalendarCheck, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Image } from "@/components/ui/image";
import { useLanguage } from "@/lib/LanguageContext";

const slides = { ar: ["دكتور توم أكثر من مجرد عيادة", "قسم الرعاية الطبية بكافة تخصصاتها على مدار 24 ساعة", "قسم الاستضافة الطبية برعاية طبية على مدار 24 ساعة", "قسم القرومنق (شاور وحلاقة) على مدار 24 ساعة", "قسم التسوق لاحتياجات أليفك على مدار 24 ساعة", "استمتع بالحديقة والممشى على مدار 24 ساعة"], en: ["Dr. Tom is more than a clinic", "Comprehensive medical care, 24 hours a day", "Medical boarding with round-the-clock care", "Professional grooming, 24 hours a day", "Pet essentials shopping, 24 hours a day", "Enjoy our garden and walking trail, 24 hours a day"] };
const bg = "https://media.base44.com/images/public/6a92a06f32c39b0226f9e8c3/2ac6403f8_generated_image.png";

export default function Hero() {
  const [i, setI] = useState(0); const { language, isArabic } = useLanguage(); const copy = slides[language];
  useEffect(() => { const t = setInterval(() => setI((p) => (p + 1) % copy.length), 5000); return () => clearInterval(t); }, [copy.length]);
  const go = (d) => setI((p) => (p + d + copy.length) % copy.length);
  return <section id="home" className="relative h-[82vh] min-h-[480px] w-full overflow-hidden"><Image src={bg} fittingType="fill" alt={isArabic ? "حيوانات أليفة في عيادة دكتور توم" : "Pets at Dr. Tom clinic"} className="absolute inset-0 w-full h-full object-cover" style={{ filter: "saturate(1.06) contrast(1.04) brightness(1.02)" }} /><div className="absolute inset-0 bg-gradient-to-b from-white/25 via-transparent to-black/30" /><div className="absolute z-10 right-4 sm:right-8 bottom-16 max-w-md text-white"><div className="rounded-3xl bg-primary/35 backdrop-blur-md border border-white/20 p-6 sm:p-7 text-right"><span className="mb-4 inline-block rounded-full bg-white/20 px-4 py-1.5 text-sm font-semibold backdrop-blur">{isArabic ? "اختر الخدمة التي تحتاجها لأليفك" : "Choose the care your pet needs"}</span><h1 key={i} className="text-2xl sm:text-4xl font-extrabold leading-tight drop-shadow-lg text-right">{copy[i]}</h1><Button asChild size="lg" className="mt-6 gap-2 text-base h-12 px-8 bg-white text-primary hover:bg-white/90"><a href="#booking"><CalendarCheck className="w-5 h-5" /> {isArabic ? "احجز موعد الآن" : "Book an appointment"}</a></Button></div></div><button onClick={() => go(-1)} className="absolute right-4 top-1/2 -translate-y-1/2 z-10 grid place-items-center w-10 h-10 rounded-full bg-white/20 text-white" aria-label={isArabic ? "السابق" : "Previous"}><ChevronRight className="w-5 h-5" /></button><button onClick={() => go(1)} className="absolute left-4 top-1/2 -translate-y-1/2 z-10 grid place-items-center w-10 h-10 rounded-full bg-white/20 text-white" aria-label={isArabic ? "التالي" : "Next"}><ChevronLeft className="w-5 h-5" /></button><div className="absolute bottom-5 inset-x-0 z-10 flex justify-center gap-2">{copy.map((_, idx) => <button key={idx} onClick={() => setI(idx)} className={`h-2 rounded-full ${idx === i ? "w-8 bg-white" : "w-2 bg-white/50"}`} aria-label={`${isArabic ? "شريحة" : "Slide"} ${idx + 1}`} />)}</div></section>;
}